server:
  port: 8888

spring:
  # mysql数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 对应 RedisProperties 类
  redis:
    host: 192.168.192.100
    port: 6379
    password: root # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。

# JWT配置
jwt:
  # 密匙Key（可考虑做配置加密处理）
  secret: booksecret.!@
  # HeaderKey
  header: Token
  # Token前缀
  prefix: Bearer
  # 过期时间，单位秒 86400
  expiration: 86400
  # 配置白名单（不需要认证）
  exclude-path: /login/**,/register/**,/static/**
